# Generated by Django 4.1.7 on 2023-03-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(default='computerscience', max_length=50)),
                ('year', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
